# Use Node.js as a base image
FROM node:22

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install any dependencies
RUN npm install

# Bundle app source
COPY . .

# Expose port and start application
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]